In [7]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\krish\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\krish\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\krish\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\krish\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 3.3 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.9 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.9 MB 3.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 3.4 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.9 MB 3.2 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 3.1 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 3.0 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 3.1 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.9 MB 3.2 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 3.1 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.0 MB/s  0:00:03
Installing collected packages: pandas
Successfully installed pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

In [9]:
pd.__version__

'3.0.2'

In [10]:
# data frame
# create data frmae
df=pd.DataFrame([11,22,33],columns=['col_name'])
print(df)
print(type(df))

   col_name
0        11
1        22
2        33
<class 'pandas.DataFrame'>

In [35]:
data ={
    'Name': ["krishna","sarthak","ramraj","shivraj"],
    'Age': [16,17,18,19],
    'Salary': [19000,70000,50000,30000]


}

In [82]:
df =pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age  Salary
0  krishna   16   19000
1  sarthak   17   70000
2   ramraj   18   50000
3  shivraj   19   30000
<class 'pandas.DataFrame'>

In [37]:
# basic dtat frmae under standing
df.head(2) # top two rows

      Name  Age  Salary
0  krishna   16   19000
1  sarthak   17   70000

In [38]:
df.tail(2)#last two rows

      Name  Age  Salary
2   ramraj   18   50000
3  shivraj   19   30000

In [39]:
df.shape

(4, 3)

In [40]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [41]:
df1=df.rename(columns={'Salary':'Monthly_Salary'})# change salary column name to monthly_salary
print(df1)

      Name  Age  Monthly_Salary
0  krishna   16           19000
1  sarthak   17           70000
2   ramraj   18           50000
3  shivraj   19           30000

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [43]:
df.describe()# all statiscal data

             Age        Salary
count   4.000000      4.000000
mean   17.500000  42250.000000
std     1.290994  22514.809941
min    16.000000  19000.000000
25%    16.750000  27250.000000
50%    17.500000  40000.000000
75%    18.250000  55000.000000
max    19.000000  70000.000000

In [44]:
# save and load csv files

In [45]:
df.to_csv('test_data.csv',index =False)# save csv file without index

In [46]:
load_df= pd.read_csv('test_data.csv')# load csv file from system
load_df

      Name  Age  Salary
0  krishna   16   19000
1  sarthak   17   70000
2   ramraj   18   50000
3  shivraj   19   30000

In [47]:
# rows column selection

In [50]:
df[['Name']]# return that column

      Name
0  krishna
1  sarthak
2   ramraj
3  shivraj

In [52]:
df.loc[df.Name=='krishna']# LOC INDEX NAME BASED

      Name  Age  Salary
0  krishna   16   19000

In [57]:
df.loc[(df.Name=='krishna')&(df.Salary>=10000)]# check both condtion

      Name  Age  Salary
0  krishna   16   19000

In [61]:
#df.iloc[0]
df.iloc[0:2]

      Name  Age  Salary
0  krishna   16   19000
1  sarthak   17   70000

In [63]:
df[df['Age']>18]

      Name  Age  Salary
3  shivraj   19   30000

In [66]:
df.where(df['Age']>=18,other = 'Not Eligible')

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2        ramraj            18         50000
3       shivraj            19         30000

In [ ]:
# rows and columns opreation

In [87]:
# add a column
df['Team']=['CEO','HR','CTO' ,'DA']
df

      Name  Age  Salary    bonus Team
0  krishna   16   19000   3800.0  CEO
1  sarthak   17   70000  14000.0   HR
2   ramraj   18   50000  10000.0  CTO
3  shivraj   19   30000   6000.0   DA

In [92]:
df ['bonus']=df['Salary']*0.2
df

      Name  Age  Salary    bonus Team
0  krishna   16   90000  18000.0  CEO
1  sarthak   17   70000  14000.0   HR
2   ramraj   18   50000  10000.0  CTO
3  shivraj   19   30000   6000.0   DA
4      ABC   21    2100    420.0  200

In [89]:
df.loc[len(df)]=['ABC',21,2100,'IT',200] # add row
df
print(type(df))

<class 'pandas.DataFrame'>

In [90]:
# update value
df.loc[0,'Salary'] = 90000
df

      Name  Age  Salary    bonus Team
0  krishna   16   90000   3800.0  CEO
1  sarthak   17   70000  14000.0   HR
2   ramraj   18   50000  10000.0  CTO
3  shivraj   19   30000   6000.0   DA
4      ABC   21    2100       IT  200

In [91]:
print(type(df))

<class 'pandas.DataFrame'>

In [102]:
# delete value
df =df .drop(df[df.Name=='ABC'].index)

In [103]:
# delte column
df.drop('bonus',axis=1)

      Name  Age  Salary Team
0  krishna   16   90000  CEO
1  sarthak   17   70000   HR
2   ramraj   18   50000  CTO
3  shivraj   19   30000   DA

In [104]:
# sprt value
df.sort_values('Salary')

      Name  Age  Salary    bonus Team
3  shivraj   19   30000   6000.0   DA
2   ramraj   18   50000  10000.0  CTO
1  sarthak   17   70000  14000.0   HR
0  krishna   16   90000  18000.0  CEO

In [106]:
# workinbg with date value
df["DOJ"] = ["2024-01-01","2024-02-15", "2024-03-10","2024-04-20"]
df

      Name  Age  Salary    bonus Team         DOJ
0  krishna   16   90000  18000.0  CEO  2024-01-01
1  sarthak   17   70000  14000.0   HR  2024-02-15
2   ramraj   18   50000  10000.0  CTO  2024-03-10
3  shivraj   19   30000   6000.0   DA  2024-04-20

In [110]:
#convert it into date data type 
df['DOJ']=pd.to_datetime(df['DOJ'])

In [111]:
# if format is not same
df1=df

In [120]:
df1["DOJ2"] = ["16-10-2009","30-11-2018", "11-12-2009","15-11-2009"]
df1

      Name  Age  Salary    bonus Team        DOJ        DOJ2
0  krishna   16   90000  18000.0  CEO 2024-01-01  16-10-2009
1  sarthak   17   70000  14000.0   HR 2024-02-15  30-11-2018
2   ramraj   18   50000  10000.0  CTO 2024-03-10  11-12-2009
3  shivraj   19   30000   6000.0   DA 2024-04-20  15-11-2009

In [122]:
df1['DOJ2']=pd.to_datetime(df1['DOJ2'],format='%d-%m-%Y')# we have to give instsuction abvout format

In [124]:
df= df.drop('DOJ2',axis=1)

In [129]:
df['DOJ'].dt.year
df["DOJ"].dt.month
df["DOJ"].dt.day
df["DOJ"].dt.day_name()
df["DOJ"].dt.month_name()

0     January
1    February
2       March
3       April
Name: DOJ, dtype: str

In [130]:
df ['DOJ']+ pd.Timedelta(days=90)# add thsese  dates to date

0   2024-03-31
1   2024-05-15
2   2024-06-08
3   2024-07-19
Name: DOJ, dtype: datetime64[us]

In [131]:
df.isnull()

    Name    Age  Salary  bonus   Team    DOJ
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [134]:
import numpy as np
df.loc[df.Name=='shivraj','Salary']=np.nan
df

      Name  Age   Salary    bonus Team        DOJ
0  krishna   16  90000.0  18000.0  CEO 2024-01-01
1  sarthak   17  70000.0  14000.0   HR 2024-02-15
2   ramraj   18  50000.0  10000.0  CTO 2024-03-10
3  shivraj   19      NaN   6000.0   DA 2024-04-20

In [136]:
df.isnull()

    Name    Age  Salary  bonus   Team    DOJ
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False    True  False  False  False

In [137]:
df.fillna(0)

      Name  Age   Salary    bonus Team        DOJ
0  krishna   16  90000.0  18000.0  CEO 2024-01-01
1  sarthak   17  70000.0  14000.0   HR 2024-02-15
2   ramraj   18  50000.0  10000.0  CTO 2024-03-10
3  shivraj   19      0.0   6000.0   DA 2024-04-20

In [139]:
df.loc[df.Name=='shivraj','Salary']=30000

In [ ]:
# agresagtion and group by

In [141]:


df["Month"] = df["DOJ"].dt.month

In [142]:
df["Month"].value_counts()

Month
1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [144]:
df.groupby('Month')['Salary'].sum()

Month
1    90000.0
2    70000.0
3    50000.0
4    30000.0
Name: Salary, dtype: float64